name: example

on:
  pull_request:
    branches:
      - main

jobs:
  # In the event two commits are made in relatively short intervals, the approve job
  # can mark approved to the PR without being dismissed by the second commit changes,
  # which may be in violation with the workflows checks
  pre_condition:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Lint Scripts
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          path: '.'
          pattern: '*.sh'
          exclude: './.git/*'
      - name: Lint Yaml
        uses: ibiqlik/action-yamllint@v1
      - name: Lint Markdown
        uses: avto-dev/markdown-lint@v1
        with:
          args: '.'
  approve:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Generate token
        id: generate_token
        uses: bubkoo/use-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PEM }}
      - name: Get App Installation Token
        run: |
          echo "This token is masked: ${TOKEN}"
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
      - uses: hmarr/auto-approve-action@v2.0.0
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
